apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: exam-app
type: Opaque
stringData:
  sa-password: "MyStrongPassword123!"
  connection-string: "Server=sql-server.exam-app.svc.cluster.local;Database=ExamWebMarket;User Id=sa;Password=MyStrongPassword123!;TrustServerCertificate=true;"